### ISSUE TITLE
Signature verification broken with files larger than 887 bytes

### ISSUE THREAD

**Issue by heikkiorsila** [covert-encryption/covert#79]
Encrypting and signing a file with an SSH public/private key fails when file size is larger than 887 bytes.
```
$ dd if=/dev/random of=file count=1 bs=887 && covert enc -R test.pub -i test -o archive.enc file && covert dec -i test -o tempdir archive.enc
...
... Signature verified
$ dd if=/dev/random of=file count=1 bs=888 && covert enc -R test.pub -i test -o archive.enc file && covert dec -i test -o tempdir archive.enc
...
Error: Missing signature block (needed 80 bytes, got 0)
```

**Comment by covert-encryption** [comment]
Looks like a blockstream bug. 1024 is the relevant limit (on total encrypted file size), after which there will be more than one block, and 888 bytes of data plus headers, structures and random padding probably happens to hit that for you. Will look into this. Thanks for reporting.

**Comment by covert-encryption** [comment]
@heikkiorsila Mind reviewing that PR?
