### ISSUE TITLE
Policy for reporting security vulnerabilities

### ISSUE THREAD

**Issue by hddqsb** [covert-encryption/covert#96]
Hi, what's the process for reporting security vulnerabilities?

(FYI: GitHub automatically treats the file *docs/Security.md* as the project's [security policy](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository), but that file actually contains information about the encryption format rather than instructions for reporting security vulnerabilities.)

**Comment by covert-encryption** [comment]
At this point in public issues, as the software is not considered stable or recommended for end users. Good point on the file name, will change that.
