### ISSUE TITLE
qcovert needs dependencies: PySide6 and showinfm

### ISSUE THREAD

**Issue by apatheticposture** [covert-encryption/covert#97]
Installing covert from pip, a few dependencies weren't pulled into my system required for **qcovert** to run properly:

- PySide6 (pip install pyside6)
- showinfm (pip install show-in-file-manager)

These don't appear to be part of any default install on my Kubuntu system, at least.

**Comment by covert-encryption** [comment]
Those dependencies are included in setup.py as extras when `covert[gui]` is specified. Did you install with this flag? I believe that pip installs the `qcovert` startup script even when not requested for, but doesn't then pull the requirements, and unfortunately that seems unavoidable unless the software is broken to separate packages.

**Comment by covert-encryption** [comment]
Closing as this appears a setuptools/pip issue that cannot be easily resolved in Covert.
